/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MkAnyEmoji: typeof import('./components/MkAnyEmoji.vue')['default']
    MkAvatar: typeof import('./components/MkAvatar.vue')['default']
    MkCode: typeof import('./components/MkCode.vue')['default']
    MkCustomEmoji: typeof import('./components/MkCustomEmoji.vue')['default']
    MkEmoji: typeof import('./components/MkEmoji.vue')['default']
    MkGallery: typeof import('./components/MkGallery.vue')['default']
    MkMention: typeof import('./components/MkMention.vue')['default']
    MkMfm: typeof import('./components/MkMfm.vue')['default']
    MkNote: typeof import('./components/MkNote.vue')['default']
    MkNoteReactions: typeof import('./components/MkNoteReactions.vue')['default']
    MkNotes: typeof import('./components/MkNotes.vue')['default']
    MkNotification: typeof import('./components/MkNotification.vue')['default']
    'MkNotification.NoteEvent': typeof import('./components/MkNotification.NoteEvent.vue')['default']
    'MkNotification.Reaction': typeof import('./components/MkNotification.Reaction.vue')['default']
    'MkNotification.WithNote': typeof import('./components/MkNotification.WithNote.vue')['default']
    MkNotificationNoteEvent: typeof import('./components/MkNotificationNoteEvent.vue')['default']
    MkNotifications: typeof import('./components/MkNotifications.vue')['default']
    MkUrl: typeof import('./components/MkUrl.vue')['default']
    MkUserName: typeof import('./components/MkUserName.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
