/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/AppBar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MkCode: typeof import('./components/MkCode.vue')['default']
    MkCustomEmoji: typeof import('./components/MkCustomEmoji.vue')['default']
    MkEmoji: typeof import('./components/MkEmoji.vue')['default']
    MkGallery: typeof import('./components/MkGallery.vue')['default']
    MkMention: typeof import('./components/MkMention.vue')['default']
    MkMfm: typeof import('./components/MkMfm.vue')['default']
    MkNote: typeof import('./components/MkNote.vue')['default']
    MkNotes: typeof import('./components/MkNotes.vue')['default']
    MkUrl: typeof import('./components/MkUrl.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
