/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBottomNavigation: typeof import('./components/AppBottomNavigation.vue')['default']
    AppPopupMessageContainer: typeof import('./components/AppPopupMessageContainer.vue')['default']
    AppRightSidebar: typeof import('./components/AppRightSidebar.vue')['default']
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppSnackbarQueueContainer: typeof import('./components/AppSnackbarQueueContainer.vue')['default']
    MkAnyEmoji: typeof import('./components/MkAnyEmoji.vue')['default']
    MkAvatar: typeof import('./components/MkAvatar.vue')['default']
    MkCode: typeof import('./components/MkCode.vue')['default']
    MkCustomEmoji: typeof import('./components/MkCustomEmoji.vue')['default']
    MkEmoji: typeof import('./components/MkEmoji.vue')['default']
    MkEmojiPicker: typeof import('./components/MkEmojiPicker.vue')['default']
    MkEmojiPickerEmojis: typeof import('./components/MkEmojiPickerEmojis.vue')['default']
    MkGallery: typeof import('./components/MkGallery.vue')['default']
    MkHashtag: typeof import('./components/MkHashtag.vue')['default']
    MkImage: typeof import('./components/MkImage.vue')['default']
    MkImageBlurHash: typeof import('./components/MkImageBlurHash.vue')['default']
    MkInstanceChip: typeof import('./components/MkInstanceChip.vue')['default']
    MkMention: typeof import('./components/MkMention.vue')['default']
    MkMfm: typeof import('./components/MkMfm.vue')['default']
    MkNote: typeof import('./components/MkNote.vue')['default']
    MkNoteActions: typeof import('./components/note/MkNoteActions.vue')['default']
    MkNoteBody: typeof import('./components/note/MkNoteBody.vue')['default']
    MkNoteHeader: typeof import('./components/note/MkNoteHeader.vue')['default']
    MkNotePoll: typeof import('./components/note/MkNotePoll.vue')['default']
    MkNoteReactions: typeof import('./components/note/MkNoteReactions.vue')['default']
    MkNoteRenoteBar: typeof import('./components/note/MkNoteRenoteBar.vue')['default']
    MkNotesList: typeof import('./components/note/MkNotesList.vue')['default']
    MkNoteSub: typeof import('./components/note/MkNoteSub.vue')['default']
    MkNoteText: typeof import('./components/note/MkNoteText.vue')['default']
    MkNotification: typeof import('./components/MkNotification.vue')['default']
    MkNotificationFollow: typeof import('./components/MkNotificationFollow.vue')['default']
    MkNotificationNoteEvent: typeof import('./components/MkNotificationNoteEvent.vue')['default']
    MkNotifications: typeof import('./components/MkNotifications.vue')['default']
    MkPollEditor: typeof import('./components/postform/MkPollEditor.vue')['default']
    MkPostForm: typeof import('./components/postform/MkPostForm.vue')['default']
    MkPostFormAsync: typeof import('./components/postform/MkPostFormAsync.vue')['default']
    MkPostFormCard: typeof import('./components/postform/MkPostFormCard.vue')['default']
    MkSearchNote: typeof import('./components/MkSearchNote.vue')['default']
    MkSearchUser: typeof import('./components/MkSearchUser.vue')['default']
    MkTime: typeof import('./components/MkTime.vue')['default']
    MkTimeline: typeof import('./components/MkTimeline.vue')['default']
    MkTimelines: typeof import('./components/MkTimelines.vue')['default']
    MkUrl: typeof import('./components/MkUrl.vue')['default']
    MkUserMenu: typeof import('./components/MkUserMenu.vue')['default']
    MkUserName: typeof import('./components/MkUserName.vue')['default']
    MkUserPageCard: typeof import('./components/MkUserPageCard.vue')['default']
    MkUserTimeline: typeof import('./components/MkUserTimeline.vue')['default']
    MkVisibilityPicker: typeof import('./components/postform/MkVisibilityPicker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
